# Header
menu:
  Home: /
  About: /About
  #Archives: /archives
#rss: /atom.xml

# Content
excerpt_link: Read More
fancybox: true

# Miscellaneous
google_analytics: UA-50857758-1
favicon: /favicon.png